import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  gestureRoot: {
    flex: 1,
    backgroundColor: '#f3efe4',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#f3efe4',
  },
  screen: {
    flex: 1,
    backgroundColor: '#f3efe4',
  },
  contentContainer: {
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 48,
    gap: 18,
  },
  hero: {
    backgroundColor: '#17362f',
    borderRadius: 28,
    padding: 24,
    gap: 16,
  },
  eyebrow: {
    color: '#d8ecd7',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: '#fff6e8',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 36,
  },
  heroBody: {
    color: '#d8ecd7',
    fontSize: 15,
    lineHeight: 22,
  },
  metricRow: {
    gap: 12,
  },
  metricCard: {
    backgroundColor: 'rgba(255, 246, 232, 0.1)',
    borderColor: 'rgba(255, 246, 232, 0.2)',
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  metricLabel: {
    color: '#d8ecd7',
    fontSize: 12,
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  metricValue: {
    color: '#fff6e8',
    fontSize: 18,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#fffaf1',
    borderColor: '#e4d8c3',
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    gap: 16,
    shadowColor: '#6b5a3f',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: {
      width: 0,
      height: 10,
    },
    elevation: 3,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  cardTitle: {
    color: '#1d2a28',
    fontSize: 24,
    fontWeight: '800',
  },
  cardSubtitle: {
    color: '#5f685f',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  statusBadge: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  infoRow: {
    backgroundColor: '#f7f1e5',
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  infoLabel: {
    color: '#7a725f',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  infoValue: {
    color: '#24302b',
    fontSize: 14,
    lineHeight: 20,
  },
  field: {
    gap: 8,
  },
  inlineButtonRow: {
    gap: 10,
  },
  fieldLabel: {
    color: '#2f3c38',
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    borderColor: '#d7ccb8',
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: '#fff',
    color: '#1d2a28',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  multilineInput: {
    minHeight: 112,
    textAlignVertical: 'top',
  },
  snippetCard: {
    backgroundColor: '#1f2430',
    borderRadius: 18,
    padding: 16,
    gap: 8,
  },
  snippetLabel: {
    color: '#9bd7b7',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  snippetText: {
    color: '#f1f5f3',
    fontSize: 13,
    lineHeight: 20,
  },
  actionSection: {
    gap: 10,
  },
  actionSectionTitle: {
    color: '#1d2a28',
    fontSize: 18,
    fontWeight: '800',
  },
  actionSectionDescription: {
    color: '#67726b',
    fontSize: 14,
    lineHeight: 20,
  },
  buttonGrid: {
    gap: 12,
  },
  actionTile: {
    backgroundColor: '#f7f1e5',
    borderRadius: 18,
    padding: 14,
    gap: 10,
  },
  actionTitle: {
    color: '#1f2b29',
    fontSize: 16,
    fontWeight: '800',
  },
  actionCaption: {
    color: '#667168',
    fontSize: 13,
    lineHeight: 18,
  },
  resultPanel: {
    backgroundColor: '#fff',
    borderLeftWidth: 4,
    borderRadius: 16,
    padding: 14,
    gap: 6,
  },
  resultLabel: {
    color: '#5e665f',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  resultValue: {
    color: '#1d2a28',
    fontSize: 14,
    lineHeight: 20,
  },
  mediaSectionHeader: {
    gap: 4,
  },
  mediaCountText: {
    color: '#6b746d',
    fontSize: 13,
  },
  mediaGrid: {
    gap: 12,
  },
  mediaCard: {
    backgroundColor: '#fff',
    borderColor: '#e4d8c3',
    borderRadius: 18,
    borderWidth: 1,
    overflow: 'hidden',
  },
  mediaImage: {
    width: '100%',
    height: 180,
    backgroundColor: '#e8e0d2',
  },
  mediaFallback: {
    alignItems: 'center',
    backgroundColor: '#e8e0d2',
    height: 180,
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  mediaFallbackText: {
    color: '#6f6556',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  mediaMeta: {
    gap: 6,
    padding: 14,
  },
  mediaTitle: {
    color: '#1d2a28',
    fontSize: 15,
    fontWeight: '800',
  },
  mediaCaption: {
    color: '#657168',
    fontSize: 13,
    lineHeight: 18,
  },
  previewShell: {
    overflow: 'hidden',
    borderColor: '#d7ccb8',
    borderRadius: 18,
    borderWidth: 1,
    backgroundColor: '#fff',
  },
  view: {
    height: 220,
  },
  toastWrap: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 20,
  },
  toast: {
    backgroundColor: '#1d2a28',
    borderColor: '#39524c',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    elevation: 6,
  },
  toastTitle: {
    color: '#9bd7b7',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  toastText: {
    color: '#fff6e8',
    fontSize: 14,
    lineHeight: 20,
  },
});
